### ISSUE TITLE
Error: Caught error after test environment was torn down

### ISSUE THREAD

**Issue by tmcconechy** [percy/percy-puppeteer#267]
Im having problems getting the latest version of percy to work with puppeteer.  Before this new CLI update it worked very well.

The problem seems to be that i run 23 x 3 of these tests:

```
  it('should not have visual regressions in new dark theme (percy)', async () => {
    const page = await browser.newPage();
    await page.setBypassCSP(true);
    await page.goto(url, { waitUntil: 'load' });
    await page.evaluate(() => {
      document.querySelector('ids-theme-switcher').setAttribute('mode', 'dark');
    });
    await percySnapshot(page, 'ids-textarea-new-dark');
  });
```

And at a certain point it will stop and error with
```
    : Timeout - Async callback was not invoked within the 25000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 25000 ms timeout specified by jest.setTimeout.Error:

      21 |   });
      22 |
    > 23 |   it('should not have visual regressions in new contrast theme (percy)', async () => {
         |   ^
      24 |     const page = await browser.newPage();
      25 |     await page.setBypassCSP(true);
      26 |     await page.goto(url, { waitUntil: 'load' });

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (test/ids-text/ids-text-percy-test.js:23:3)

(node:20849) UnhandledPromiseRejectionWarning: Error: Caught error after test environment was torn down

Protocol error (Page.navigate): Target closed.
    at /Users/tmcconechy/Dev/enterprise-wc/node_modules/puppeteer/src/common/Connection.ts:270:57
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/tmcconechy/Dev/enterprise-wc/node_modules/puppeteer/src/common/Connection.ts:269:12)
```

Seems like either my test is wrong but i cant see anything else i can do? Or there is some issue with percy that makes it "crash out" after a certain number of screenshots.

This is the repo/build check if this helps https://github.com/infor-design/enterprise-wc/pull/59/checks?check_run_id=2308847368#step:8:1512
Any suggestions?

**Comment by tmcconechy** [comment]
Closing this issue as I realized the problem was i was doing:
 
`const page = await browser.newPage();`

Everytime and this essentially makes a new "tab" and eventually runs out of memory. So the issue was on my side not yours.
 
Thanks !
